### ISSUE TITLE
how to use with userscript extensions?

### ISSUE THREAD

**Issue by aranapatona** [AveYo/fox#10]
I am trying to use the singleclick search with either tampermonkey or fire monkey, and I get errors in both:

![image](https://user-images.githubusercontent.com/19786351/168395354-3f46c8e1-2a3d-45be-8001-b99d2239cfd6.png)

**Comment by AveYo** [comment]
Have you searched greasemonkey / firemonkey / tampermonkey etc. script repositories for something offering the functionality?
Because chances are it's not possible in the shitty google webextension format that mozilla adopted.

I recommend using a proper, powerful user-scripts framework like the one I've made (UserChrome.js), it's all in the readme. Or [alternatives](https://www.userchrome.org/what-is-userchrome-js.html).

**Comment by aranapatona** [comment]
Thank you for your answer, yes, I have, Didn't find anything, don't use that function really often and I have one of the monkeys already installed so I figured why not try it. Installing some proper framework would be only for that specific thing in my case, so I don't think it's worth it, still after years trying to figure out wtf were FF devs thinking with the "single-click" (but actually twice or thrice) totally counter intuitive stupid clicking.

**Comment by AveYo** [comment]
mozilla devs are corporate whores that have been secretly, then on the open hating on powerusers this past decade
