### ISSUE TITLE
copilot doesnt work anymore after running the script

### ISSUE THREAD

**Issue by Luunii** [AveYo/fox#37]
title says it is there any chance you can fix this?

**Comment by AveYo** [comment]
are you serious?  
copilot IS Edge  
and yet another gimmick to get you into microsoft fauna  
resist it because you're not missing out on anything useful  

or simply do not uninstall edge
can run the script again and write edge at the end to reinstall it
then you probably need to reinstall the latest cumulative update or use vivetool to force it on

**Comment by Luunii** [comment]
ye i mean idk how much new/exclusive code it is i was just wondering if it could be run on a stub or into firefox whatever like https://github.com/anaclumos/bing-chat-for-all-browsers was and yes i know this is different and another scale but was worth a shot asking nah? i am resisting esp as this version has basically no permissions to do anything useful for advanced users and im very thankful for your work and response have a nice day
