### ISSUE TITLE
Change line scroll amount

### ISSUE THREAD

**Issue by lx30011** [AveYo/fox#5]
Compared to Chromium browsers the smooth scroll v3 preset scrolls a bit too far. I'd like to match it to Chromium behavior if possible.
Do you know which values I'd have to modify?
Thanks

**Comment by AveYo** [comment]
It should be comparable to Chrome at 3 lines per scroll for mouse.
Some mice feature their own acceleration and make it seem almost double in speed.
So in that case, set `mousewheel.system_scroll_override.enabled` to `false`
or adjust `mousewheel.system_scroll_override`.. from `200` (2x) to lower.

Since this preset is fully pixel-scrolling, there's no concept of lines anymore.
You can however make it scroll less pixels at once if that's what you want, 
by adjusting `mousewheel.default.delta_multiplier`.. from `100` to lower.
*Note that lowering this delta will also disable ability to scroll more than one screen in one-go, so for example when scrolling fast / multiple notches at once - it won't matter, scrolling will be constant speed. I prefer having that for scrolling long pages faster.* 

You should try out V4 I just shared, it's sharper, less superfluous animations at scroll end.
